
import com.kingaspx.util.BrowserUtil;
import com.kingaspx.version.Version;
import com.mysql.jdbc.Connection;
import com.teamdev.jxbrowser.chromium.Browser;
import com.teamdev.jxbrowser.chromium.dom.By;
import com.teamdev.jxbrowser.chromium.dom.DOMDocument;
import com.teamdev.jxbrowser.chromium.dom.DOMElement;
import com.teamdev.jxbrowser.chromium.dom.DOMInputElement;
import com.teamdev.jxbrowser.chromium.events.ConsoleEvent;
import com.teamdev.jxbrowser.chromium.events.FinishLoadingEvent;
import com.teamdev.jxbrowser.chromium.events.LoadAdapter;
import com.teamdev.jxbrowser.chromium.events.TitleEvent;
import com.teamdev.jxbrowser.chromium.swing.BrowserView;
import com.teamdev.jxbrowser.engine.Engine;
import com.teamdev.jxbrowser.engine.EngineOptions;
import static com.teamdev.jxbrowser.engine.RenderingMode.HARDWARE_ACCELERATED;

import java.awt.BorderLayout;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sİnan
 */
public class deneme2 extends javax.swing.JFrame {
    static int b;
    
    static String[] deneme1 = new String[2];
    static List initialCities2 = new ArrayList<city>();
    
    /**
     * Creates new form deneme2
     */
    static String musteriKonum;
    public deneme2() {
        
        initComponents();
        open_site();
        TabloDoldur(kullanıcıLabel.getText());
       // ekran2.printShortestRoute(new nearestNeighbor().findShortestRoute((ArrayList<city>) initialCities2));
        
    }
    public void TabloDoldur(String musteriadi){
        Connection connect=null;
         DB db=new DB();
         PreparedStatement statement =null;
          ResultSet rs = null;
        try {
            connect = db.getConnection();
            String sql="select * from kargo.musteri where musteriadi='"+musteriadi+"'";
            statement=connect.prepareStatement(sql);
             rs = statement.executeQuery();
             tablo.setModel(DbUtils.resultSetToTableModel (rs));
             connect.close();
        } catch (SQLException ex) {
            Logger.getLogger(deneme2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
     public void  KonumUpdate (String musteriadi,String lokasyonx,String lokasyony) throws SQLException{
         Connection connect=null;
         DB db=new DB();
         PreparedStatement statement =null;
         
         try{
         connect = db.getConnection();
         String sql="Update kargo.musteri set musterilokasyonx='"+lokasyonx+"',musterilokasyony='"+lokasyony+"'  where musteriadi='"+musteriadi+"'";
         
                 
         statement=connect.prepareStatement(sql);
         
         statement.executeUpdate();

         }catch(SQLException exception){
             db.ShowError(exception);
             JOptionPane.showMessageDialog(null,"Konum Eklenemedi Güncellenemedi");
         }finally{
             statement.close();
             connect.close();
         }
          
    }
     public void labelDoldur(String isim){
         kullanıcıLabel.setText(isim);
     }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        tablo_panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablo = new javax.swing.JTable();
        kullanıcıLabel = new javax.swing.JLabel();
        kargoYeriButonu = new javax.swing.JButton();
        AramaButonu = new keeptoo.KButton();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jTextField1 = new javax.swing.JTextField();
        map_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        temizleme = new javax.swing.JButton();
        geriButonu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 153, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(223, 112, 30));

        tablo.setBackground(new java.awt.Color(52, 66, 70));
        tablo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));
        tablo.setForeground(new java.awt.Color(255, 255, 255));
        tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablo);

        javax.swing.GroupLayout tablo_panelLayout = new javax.swing.GroupLayout(tablo_panel);
        tablo_panel.setLayout(tablo_panelLayout);
        tablo_panelLayout.setHorizontalGroup(
            tablo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        tablo_panelLayout.setVerticalGroup(
            tablo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        kargoYeriButonu.setBackground(new java.awt.Color(52, 66, 70));
        kargoYeriButonu.setForeground(new java.awt.Color(255, 255, 255));
        kargoYeriButonu.setText("Kargo Konumu Seç");
        kargoYeriButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kargoYeriButonuActionPerformed(evt);
            }
        });

        AramaButonu.setText("Ara");
        AramaButonu.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        AramaButonu.setkBackGroundColor(new java.awt.Color(0, 255, 0));
        AramaButonu.setkHoverForeGround(new java.awt.Color(0, 255, 0));
        AramaButonu.setkSelectedColor(new java.awt.Color(0, 255, 0));
        AramaButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AramaButonuActionPerformed(evt);
            }
        });

        kGradientPanel1.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkFillBackground(false);
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jTextField1.setBorder(null);
        jTextField1.setOpaque(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 320, 60));

        map_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                map_panelMouseClicked(evt);
            }
        });
        map_panel.setLayout(new java.awt.BorderLayout());
        map_panel.add(jLabel1, java.awt.BorderLayout.CENTER);

        temizleme.setBackground(new java.awt.Color(52, 66, 70));
        temizleme.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        temizleme.setForeground(new java.awt.Color(255, 255, 255));
        temizleme.setText("Temizle");
        temizleme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temizlemeActionPerformed(evt);
            }
        });

        geriButonu.setBackground(new java.awt.Color(52, 66, 70));
        geriButonu.setForeground(new java.awt.Color(255, 255, 255));
        geriButonu.setText("Geri Dön");
        geriButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriButonuActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/3.jpeg"))); // NOI18N

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                        .addComponent(AramaButonu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(temizleme, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kargoYeriButonu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(geriButonu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kullanıcıLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(map_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 1118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tablo_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addComponent(map_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(tablo_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kullanıcıLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(AramaButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(temizleme, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kargoYeriButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(geriButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 660));

        setSize(new java.awt.Dimension(1518, 703));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AramaButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AramaButonuActionPerformed
        // TODO add your handling code here:
        DOMDocument dosya = browser.getDocument();
        DOMElement lokasyon = dosya.findElement(By.id("address"));
        DOMElement arama = dosya.findElement(By.id("submit"));
        DOMInputElement butonumuz = (DOMInputElement) arama;
        DOMInputElement konum = (DOMInputElement) lokasyon;
        konum.setValue(jTextField1.getText());
        butonumuz.click();
        
    }//GEN-LAST:event_AramaButonuActionPerformed

    private void temizlemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temizlemeActionPerformed
        // TODO add your handling code here:
        browser.reload();
        jTextField1.setText(null);
    }//GEN-LAST:event_temizlemeActionPerformed

    private void kargoYeriButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kargoYeriButonuActionPerformed
        
        try {
            
             Connection connect=null;
         DB db=new DB();
         PreparedStatement statement =null;
         
         try{
         connect = db.getConnection();
         String sql="Update kargo.musteri set musteriteslimatdurumu='Teslim Edilmedi' where musteriadi='"+kullanıcıLabel.getText()+"'";
         
                 
         statement=connect.prepareStatement(sql);
         
         statement.executeUpdate();

         }catch(SQLException exception){
             db.ShowError(exception);
             JOptionPane.showMessageDialog(null,"Konum Eklenemedi Güncellenemedi");
         }finally{
             statement.close();
             connect.close();
         }
            
            TabloDoldur(kullanıcıLabel.getText());
                 deneme1 = jTextField1.getText().split(",");
                 String lokasyonx=deneme1[0];
                 String lokasyony=deneme1[1];
                      Main.ekran.initialCities.add(new city(kullanıcıLabel.getText(),Double.parseDouble(lokasyonx),Double.parseDouble(lokasyony)));
                      Main.ekran.initialCities.addAll(Main.deneme.initialCities2);
                      Main.ekran.printShortestRoute(new nearestNeighbor().findShortestRoute((ArrayList<city>) Main.ekran.initialCities));
                      /*Main.deneme.initialCities2.add(new city(kullanıcıLabel.getText(),Double.parseDouble(lokasyonx),Double.parseDouble(lokasyony)));
                      Main.ekran.initialCities.addAll(Main.deneme.initialCities2);
                      Main.ekran.printShortestRoute(new nearestNeighbor().findShortestRoute((ArrayList<city>) Main.ekran.initialCities));*/
                      Main.ekran.setVisible(false);
            KonumUpdate(kullanıcıLabel.getText(),lokasyonx,lokasyony);
            DOMDocument dosya = browser.getDocument();
            DOMElement lokasyon = dosya.findElement(By.id("address"));
            DOMElement arama = dosya.findElement(By.id("submit"));
            DOMInputElement butonumuz = (DOMInputElement) arama;
            DOMInputElement konum = (DOMInputElement) lokasyon;
            konum.setValue(jTextField1.getText());
            butonumuz.click();
            
            Main.ekran.TabloDoldur();
            Main.ekran.Isaretle();
            Main.ekran.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(deneme2.class.getName()).log(Level.SEVERE, null, ex);
        }
        TabloDoldur(kullanıcıLabel.getText());
                   
    }//GEN-LAST:event_kargoYeriButonuActionPerformed

    private void geriButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriButonuActionPerformed
                    /*GirisEkrani1 menu6=new GirisEkrani1();
                    menu6.setSize(570,600);
                    menu6.setVisible(true);*/
                    
                    Main.menu3.setSize(570, 600);
                    Main.menu3.setVisible(true);
                    Main.deneme.setVisible(false);
                    Main.ekran.setVisible(false);
                    
    }//GEN-LAST:event_geriButonuActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void map_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_map_panelMouseClicked
        System.out.println("tıkladın");
    }//GEN-LAST:event_map_panelMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        Engine engine = Engine.newInstance(
        EngineOptions.newBuilder(HARDWARE_ACCELERATED)
                .licenseKey("1BNDHFSC1G0MVB5HR3MMFAGLZXW35IMQGFBHWN90FSKOIZF7VUK1N4EVE0JXFRRSLKLQN8")
                .build());
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deneme2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deneme2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deneme2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deneme2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deneme2().setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton AramaButonu;
    private javax.swing.JButton geriButonu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JButton kargoYeriButonu;
    private javax.swing.JLabel kullanıcıLabel;
    private javax.swing.JPanel map_panel;
    private javax.swing.JPanel panel1;
    private javax.swing.JTable tablo;
    private javax.swing.JPanel tablo_panel;
    private javax.swing.JButton temizleme;
    // End of variables declaration//GEN-END:variables
    Browser browser;
    BrowserView view;

    private void open_site() {
        BrowserUtil.setVersion(Version.V6_22);

        browser = new Browser();
        view = new BrowserView(browser);

        map_panel.add(view, BorderLayout.CENTER);
        
         browser.addTitleListener((TitleEvent evt) -> {
            jLabel1.setText("   " + evt.getTitle());
        });

        browser.addConsoleListener((ConsoleEvent evt) -> {
            System.out.println("LOG: " + evt.getMessage());
        });

        browser.addLoadListener(new LoadAdapter() {
            @Override
            public void onFinishLoadingFrame(FinishLoadingEvent evt) {
                evt.getBrowser().setZoomLevel(-1);
            }
        });

        browser.loadURL("C:\\Users\\Sİnan\\Desktop\\deneme\\web geliştirme\\uygulama\\kargoharita.html");
    }}
