import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import com.mysql.jdbc.Connection;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import sun.misc.MessageUtils;

public class GirisEkrani1 extends javax.swing.JFrame {

    static String ad;
    static String sifre;
    static String ad2;
    public GirisEkrani1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sifreDegistir = new javax.swing.JButton();
        girisButonu = new javax.swing.JButton();
        kaydolbutonu1 = new javax.swing.JButton();
        kullaniciAdi_text = new javax.swing.JTextField();
        sifre_text = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        sifreDegistir.setBackground(new java.awt.Color(52, 66, 70));
        sifreDegistir.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        sifreDegistir.setForeground(new java.awt.Color(255, 255, 255));
        sifreDegistir.setText("SIFREMI DEGISTIR");
        sifreDegistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifreDegistirActionPerformed(evt);
            }
        });
        getContentPane().add(sifreDegistir);
        sifreDegistir.setBounds(140, 480, 310, 50);

        girisButonu.setBackground(new java.awt.Color(0, 153, 51));
        girisButonu.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        girisButonu.setText("GIRIS YAP");
        girisButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girisButonuActionPerformed(evt);
            }
        });
        getContentPane().add(girisButonu);
        girisButonu.setBounds(140, 260, 310, 50);

        kaydolbutonu1.setBackground(new java.awt.Color(52, 66, 70));
        kaydolbutonu1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        kaydolbutonu1.setForeground(new java.awt.Color(255, 255, 255));
        kaydolbutonu1.setText("KAYIT OL");
        kaydolbutonu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydolbutonu1ActionPerformed(evt);
            }
        });
        getContentPane().add(kaydolbutonu1);
        kaydolbutonu1.setBounds(140, 370, 310, 50);

        kullaniciAdi_text.setToolTipText("");
        kullaniciAdi_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullaniciAdi_textActionPerformed(evt);
            }
        });
        getContentPane().add(kullaniciAdi_text);
        kullaniciAdi_text.setBounds(150, 100, 320, 22);

        sifre_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifre_textActionPerformed(evt);
            }
        });
        getContentPane().add(sifre_text);
        sifre_text.setBounds(150, 160, 320, 22);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel7.setText("KULLANICI ADI:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 100, 80, 20);

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel9.setText("SIFRE:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 160, 90, 20);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 570, 600);

        jPanel1.setBackground(new java.awt.Color(223, 112, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/3.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(148, 148, 148))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(569, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 570, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sifre_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifre_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sifre_textActionPerformed

    private void kullaniciAdi_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullaniciAdi_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kullaniciAdi_textActionPerformed

    private void sifreDegistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifreDegistirActionPerformed
        setVisible(false);
        sifreDegistir menu2 = new sifreDegistir();
        menu2.setSize(570, 600);
        menu2.setVisible(true);
    }//GEN-LAST:event_sifreDegistirActionPerformed
static int z;
public void girisSorgu(){
        ad=kullaniciAdi_text.getText();
        sifre=sifre_text.getText();
         String sql_sorgu="select count(idmusteri) as giris from musteri where musteriadi='"+ad+"'and musterisifre='"+sifre+"'";

        ResultSet rs=DB.basla();
        rs=DB.sorgulama(sql_sorgu);
        try {
            while (rs.next()) {
                if (rs.getInt("giris")==1) {
                    GirisEkrani1.z=1;
                }
            }
        } catch (SQLException ex) {            
            Logger.getLogger(GirisEkrani1.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"HATA!!!");
        }
}
    private void girisButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girisButonuActionPerformed
      
        Main.menu3.ad=kullaniciAdi_text.getText();
        sifre=sifre_text.getText();
         String sql_sorgu="select count(idmusteri) as giris from musteri where musteriadi='"+ad+"'and musterisifre='"+sifre+"'";

        ResultSet rs=DB.basla();
        rs=DB.sorgulama(sql_sorgu);
        try {
            while (rs.next()) {
                if (rs.getInt("giris")==1) {
                    
                    Main.menu3.ad2=kullaniciAdi_text.getText();
                    Main.deneme.TabloDoldur(ad2);
                    Main.deneme.labelDoldur(ad2);
                    Main.deneme.setSize(1500,700);
                    Main.deneme.setVisible(true);
                    Main.ekran.setVisible(true);
                    Main.ekran.setSize(2000, 700);
                    setVisible(false);
                    
                } else {
                    JOptionPane.showMessageDialog(null,"Giris yapilamadi");
                }
                
            }
        } catch (SQLException ex) {            
            Logger.getLogger(GirisEkrani1.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"HATA!!!");
        }
    }//GEN-LAST:event_girisButonuActionPerformed

    private void kaydolbutonu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydolbutonu1ActionPerformed
        KaydolEkrani menu =new KaydolEkrani();
        menu.setSize(570,600);
        menu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_kaydolbutonu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                
               
             
            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton girisButonu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kaydolbutonu1;
    private javax.swing.JTextField kullaniciAdi_text;
    private javax.swing.JButton sifreDegistir;
    private javax.swing.JTextField sifre_text;
    // End of variables declaration//GEN-END:variables
}
