
import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sİnan
 */
public class sifreDegistir extends javax.swing.JFrame {

    /**
     * Creates new form sifreDegistir
     */
    public sifreDegistir() {
        initComponents();
    }
    public void  SifreDegistir (String musteriadi, String sifre) throws SQLException{
         Connection connect=null;
         DB db=new DB();
         PreparedStatement statement =null;
         
         try{
         connect = db.getConnection();
         String sql="Update musteri set musterisifre='"+sifre+"' where musteriadi='"+musteriadi+"'";
         statement=connect.prepareStatement(sql);
         statement.executeUpdate();
         JOptionPane.showMessageDialog(null,"Sifre Degistirildi");
         }catch(SQLException exception){
             db.ShowError(exception);
             JOptionPane.showMessageDialog(null,"Sifre Degistirilemedi");
         }finally{
             statement.close();
             connect.close();
         }
      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kullaniciAdi_text1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        sifreDegistir = new javax.swing.JButton();
        sifre_text = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        kullaniciAdi_text1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullaniciAdi_text1ActionPerformed(evt);
            }
        });
        getContentPane().add(kullaniciAdi_text1);
        kullaniciAdi_text1.setBounds(140, 60, 320, 22);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel7.setText("KULLANICI ADI:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 60, 80, 20);

        sifreDegistir.setBackground(new java.awt.Color(0, 153, 51));
        sifreDegistir.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        sifreDegistir.setText("SIFREMI DEGISTIR");
        sifreDegistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifreDegistirActionPerformed(evt);
            }
        });
        getContentPane().add(sifreDegistir);
        sifreDegistir.setBounds(120, 210, 310, 50);

        sifre_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifre_textActionPerformed(evt);
            }
        });
        getContentPane().add(sifre_text);
        sifre_text.setBounds(140, 130, 320, 22);

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel9.setText("YENI SIFRE:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 130, 90, 20);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 570, 600);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/3.jpeg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(171, 290, 310, 200);

        jPanel1.setBackground(new java.awt.Color(223, 112, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 570, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sifre_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifre_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sifre_textActionPerformed

    private void sifreDegistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifreDegistirActionPerformed
        try {
            SifreDegistir(kullaniciAdi_text1.getText(), sifre_text.getText());
            Main.menu3.setSize(570, 750);
            Main.menu3.setVisible(true);
            setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(sifreDegistir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sifreDegistirActionPerformed

    private void kullaniciAdi_text1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullaniciAdi_text1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kullaniciAdi_text1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sifreDegistir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sifreDegistir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sifreDegistir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sifreDegistir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sifreDegistir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField kullaniciAdi_text1;
    private javax.swing.JButton sifreDegistir;
    private javax.swing.JTextField sifre_text;
    // End of variables declaration//GEN-END:variables
}
